### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by valentinbesse** [JBeaudaux/Flocon#3]
A login page should be available to connect people.

## Workflow
1. Access to the login page,
2. Select sign up or sign in,
3. Add email and password,
4. Proceed to authentication: check email/password,
5. Proceed to authorization: check role and redirect to corresponding page,
6. If role is user, proceed to connection to Moralis using Metamask,
7. Get Metamask user address (wallet address).

## Tasks

- [x] Link landing page and login page,
- [x] Implement Moralis framework to use Metamask,
- [x] Get Wallet User Address,
- [ ] Implement sign in/sign up controller,
- [ ] Check role,
- [ ] Redirect to corresponding page.
